spring:
  profiles:
   active: zone1
   default: zone1
  zipkin:
    baseUrl: http://localhost:9411/
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/erp_db
    username: erp_user
    password: password
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true    



# Discovery server access
eureka:
  client:
    prefer-same-zone-eureka: true
    region: region-1
    service-url:
      zone1: http://localhost:8761/eureka/
      zone2: http://127.0.0.1:8762/eureka/
    availability-zones:
      region-1: zone1,zone2
      
      


    
#Expose all metrics to Admin Server
management.endpoints.web.exposure.include: '*'

health:
 config:
    enabled: false
management:
  security:
    enabled: false


# Tell Feign to enable Hystrix
feign:
  hystrix:
    enabled: true

# Disable Hystrix timeout globally (for all services)
# Increase the Hystrix timeout to 10s (globally)

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 10000
            
# Increase the Ribbon timeout to 30s (globally)
ribbon:
    eureka:
        enabled: true
    ConnectTimeout: 30000
    ReadTimeout: 30000




  

    
  