/*
 * This file is generated by jOOQ.
*/
package com.sbn.erp.domain;


import com.sbn.erp.domain.tables.HibernateSequence;
import com.sbn.erp.domain.tables.Product;
import com.sbn.erp.domain.tables.ProductCategory;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ErpDb extends SchemaImpl {

    private static final long serialVersionUID = -415035114;

    /**
     * The reference instance of <code>erp_db</code>
     */
    public static final ErpDb ERP_DB = new ErpDb();

    /**
     * The table <code>erp_db.hibernate_sequence</code>.
     */
    public final HibernateSequence HIBERNATE_SEQUENCE = com.sbn.erp.domain.tables.HibernateSequence.HIBERNATE_SEQUENCE;

    /**
     * The table <code>erp_db.product</code>.
     */
    public final Product PRODUCT = com.sbn.erp.domain.tables.Product.PRODUCT;

    /**
     * The table <code>erp_db.product_category</code>.
     */
    public final ProductCategory PRODUCT_CATEGORY = com.sbn.erp.domain.tables.ProductCategory.PRODUCT_CATEGORY;

    /**
     * No further instances allowed
     */
    private ErpDb() {
        super("erp_db", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            HibernateSequence.HIBERNATE_SEQUENCE,
            Product.PRODUCT,
            ProductCategory.PRODUCT_CATEGORY);
    }
}
