/*
 * This file is generated by jOOQ.
*/
package com.sbn.erp.domain;


import com.sbn.erp.domain.tables.Product;
import com.sbn.erp.domain.tables.ProductCategory;
import com.sbn.erp.domain.tables.records.ProductCategoryRecord;
import com.sbn.erp.domain.tables.records.ProductRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>erp_db</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = UniqueKeys0.KEY_PRODUCT_PRIMARY;
    public static final UniqueKey<ProductCategoryRecord> KEY_PRODUCT_CATEGORY_PRIMARY = UniqueKeys0.KEY_PRODUCT_CATEGORY_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = Internal.createUniqueKey(Product.PRODUCT, "KEY_product_PRIMARY", Product.PRODUCT.ID);
        public static final UniqueKey<ProductCategoryRecord> KEY_PRODUCT_CATEGORY_PRIMARY = Internal.createUniqueKey(ProductCategory.PRODUCT_CATEGORY, "KEY_product_category_PRIMARY", ProductCategory.PRODUCT_CATEGORY.ID);
    }
}
