/*
 * This file is generated by jOOQ.
*/
package com.sbn.erp.domain;


import com.sbn.erp.domain.tables.HibernateSequence;
import com.sbn.erp.domain.tables.Product;
import com.sbn.erp.domain.tables.ProductCategory;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in erp_db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>erp_db.hibernate_sequence</code>.
     */
    public static final HibernateSequence HIBERNATE_SEQUENCE = com.sbn.erp.domain.tables.HibernateSequence.HIBERNATE_SEQUENCE;

    /**
     * The table <code>erp_db.product</code>.
     */
    public static final Product PRODUCT = com.sbn.erp.domain.tables.Product.PRODUCT;

    /**
     * The table <code>erp_db.product_category</code>.
     */
    public static final ProductCategory PRODUCT_CATEGORY = com.sbn.erp.domain.tables.ProductCategory.PRODUCT_CATEGORY;
}
